package com.derrick.cart

const val CHECKLIST_POSITION = "EXTRA_CHECKLIST_POSITION"
const val CHECKLIST_ITEM_POSITION = "EXTRA_CHECKLIST_ITEM_POSITION"
const val CHECKLIST = "EXTRA_CHECKLIST"
const val CHECKLIST_ITEM = "EXTRA_CHECKLIST_ITEM"
const val POSITION_NOT_SET = -1
